services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Dla\DlaOpacNg\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true

  Dla\DlaOpacNg\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Ajax/EidSettings.php'