services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Dla\DlaOpacNg\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    public: true

  Dla\DlaOpacNg\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Ajax/EidSettings.php'
      - '../Classes/Find/'

  # Klassen der ehemaligen Extension dla/find
  Dla\Find\:
    resource: '../Classes/Find/*'
    public: false
    exclude: '../Classes/Find/Ajax/EidSettings.php'

  Dla\Find\ViewHelpers\:
    resource: '../Classes/Find/ViewHelpers/*'
    public: true

  Dla\DlaOpacNg\Cli\Import:
    tags:
      - name: console.command
        command: 'dla_opac_ng:import'
        description: 'Import new collection hierarchy into database.'